### ISSUE TITLE
Not working after updates?

### ISSUE THREAD

**Issue by aca** [keymasterr/Firefox-UI-Theme-Tweaks-and-Bottom-Tabs#1]
![image](https://user-images.githubusercontent.com/50316549/70296453-0afaeb00-182e-11ea-88f9-370c4ea41ffd.png)

Thanks for this great configuration. I love this. But stopped working after updates.
I know little about this stuffs. Can't find the reason.

```
firefox
  version 	71.0
  Build ID 	20191202093317

OS
  macOS 10.15.1 19B88 x86_64
```

**Comment by keymasterr** [comment]
It should work now. Somehow.

Devs have changed the structure a little and I'm not sure I got all the scenarios covered now though.

**Comment by aca** [comment]
@keymasterr Thanks! Working great!
