### ISSUE TITLE
Incorrect cut-off

### ISSUE THREAD

**Issue by TadaCZE** [keymasterr/Firefox-UI-Theme-Tweaks-and-Bottom-Tabs#3]
The tab is cut off in customize firefox tab (wrote a fix):
`:root:not([inDOMFullscreen]) #browser, :root:not([inDOMFullscreen]) #customization-container {
  margin-bottom: var(--tbh);
}`

**Comment by keymasterr** [comment]
Thank you, I've added your fix to the code
